# Streamlit Secrets Configuration
# OpenAI API key (Replace with your actual API key)
OPENAI_API_KEY = "your-openai-api-key-here"

# Instructions:
# 1. Get your API key from https://platform.openai.com/account/api-keys
# 2. Replace "your-openai-api-key-here" with your actual API key
# 3. Save this file
# 4. The app will automatically use this API key

# Example:
# OPENAI_API_KEY = "sk-1234567890abcdef..."
